export const LinkData = [
    {
        _id:1,
        title:"Home",
        link:"home",
    },
    {
        _id:2,
        title:"Features",
        link:"features",
    },
    {
        _id:3,
        title:"Projects",
        link:"projects",
    },
    {
        _id:4,
        title:"Resume",
        link:"resume",
    },
    {
        _id:5,
        title:"Tutorials",
        link:"tutorials",
    },
    {
        _id:6,
        title:"Contact",
        link:"contact",
    }
    
];